AFM_DiDSideConfig {
 m_sFactionKey "FIA"
 m_sDisplayName "FIA Partisans"
 m_aInfantryGroups {
  "{5BEA04939D148B1D}Prefabs/Groups/INDFOR/Group_FIA_FireTeam.et"
  "{1BB20A4B3A53D0F5}Prefabs/Groups/INDFOR/Group_FIA_LightFireTeam.et"
  "{22F33D3EC8F281AB}Prefabs/Groups/INDFOR/Group_FIA_MachineGunTeam.et"
  "{2CC26054775FBA2C}Prefabs/Groups/INDFOR/Group_FIA_Team_AT.et"
  "{CE41AF625D05D0F0}Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
  "{2E9C920C3ACA2C6F}Prefabs/Groups/INDFOR/Group_FIA_ReconTeam.et"
  "{6E725D44CA973C24}Prefabs/Groups/INDFOR/Group_FIA_SentryTeam.et"
  "{6307F42403E9B8A4}Prefabs/Groups/INDFOR/Group_FIA_SharpshooterTeam.et"
 }
 m_aMechanized {
  AFM_DiDVehicleEntry "{A64868C6E8BD76B7}" {
   m_sVehiclePrefab "{F7E9AA0C813EABDA}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_FIA.et"
   m_CrewConfig AFM_CrewConfig "{7FD40B8AA8DF34B0}" {
    m_sDriverPrefab "{641AD7731E23454B}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Crew.et"
    m_sGunnerPrefab "{58E47E5A4D599432}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_MG.et"
   }
  }
  AFM_DiDVehicleEntry "{32B8A85C103F2805}" {
   m_sVehiclePrefab "{B47110AA1A806556}Prefabs/Vehicles/Wheeled/BTR70/BTR70_FIA.et"
   m_CrewConfig AFM_CrewConfig "{0F3DC096D825DCD7}" {
    m_sDriverPrefab "{641AD7731E23454B}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Crew.et"
    m_sGunnerPrefab "{58E47E5A4D599432}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_MG.et"
   }
  }
 }
 m_sMortarComposition "{CE635E91D1F3B5FF}Prefabs/Compositions/DiD_MortarComposition_FIA.et"
 m_MortarCrew AFM_CrewConfig "{F69586410E996F98}" {
  m_sDriverPrefab ""
  m_sGunnerPrefab "{066644E57BA1E26E}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Sapper.et"
  m_bSpawnDriver 0
  m_bNoTurretDismount 0
 }
 m_sCowabungaGroup "{242BC3C6BCE96EA5}Prefabs/Groups/INDFOR/Group_FIA_Base.et"
 m_aCowabungaCharacters {
  "{854C04F0EA2129CC}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Unarmed.et"
 }
 m_aPlayerCharacters {
  "{FE65E8C60C751352}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_PL.et"
  "{677B515F119222C2}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_SL.et"
  "{45A02CA25CBA9443}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Medic.et"
  "{58E47E5A4D599432}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_MG.et"
  "{D25BC9815A9F9E8D}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_AT.et"
  "{BF1E43FF39AA526B}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Scout.et"
  "{CE33AB22F61F3365}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Sharpshooter.et"
  "{84B40583F4D1B7A3}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Rifleman.et"
 }
 m_sExtractionHelicopter "{BDE43262FC05B4D7}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_empty_sharkNose.et"
 m_sExtractionCrewGroup "{BF78D4AAF08466CD}Prefabs/Groups/BLUFOR/REAPER_US_HelicopterCrew.et"
}