AFM_DiDSideConfig {
 m_sFactionKey "US"
 m_sDisplayName "US Army"
 m_sExtractionHelicopter "{BDE43262FC05B4D7}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_empty_sharkNose.et"
 m_sExtractionCrewGroup "{BF78D4AAF08466CD}Prefabs/Groups/BLUFOR/REAPER_US_HelicopterCrew.et"
}