AFM_DiDSideConfig {
 m_sFactionKey "US"
 m_sDisplayName "US Army"
 m_aInfantryGroups {
  "{84E5BBAB25EA23E5}Prefabs/Groups/BLUFOR/Group_US_FireTeam.et"
  "{FCF7F5DC4F83955C}Prefabs/Groups/BLUFOR/Group_US_LightFireTeam.et"
  "{958039B857396B7B}Prefabs/Groups/BLUFOR/Group_US_MachineGunTeam.et"
  "{DE747BC9217D383C}Prefabs/Groups/BLUFOR/Group_US_Team_GL.et"
  "{FAEA8B9E1252F56E}Prefabs/Groups/BLUFOR/Group_US_Team_LAT.et"
  "{DDF3799FA1387848}Prefabs/Groups/BLUFOR/Group_US_RifleSquad.et"
  "{F65B7BB712F46FEE}Prefabs/Groups/BLUFOR/Group_US_ReconTeam.et"
  "{3BF36BDEEB33AEC9}Prefabs/Groups/BLUFOR/Group_US_SentryTeam.et"
 }
 m_aMechanized {
  AFM_DiDVehicleEntry "{955243EE065CB27D}" {
   m_sVehiclePrefab "{5168FEA3054D6D15}Prefabs/Vehicles/Wheeled/M151A2/M151A2_M2HB_MERDC.et"
   m_CrewConfig AFM_CrewConfig "{078E9B0A36B31387}" {
    m_sDriverPrefab "{E1CB513B8B9B08F4}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Crew.et"
    m_sGunnerPrefab "{26A9756790131354}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Rifleman.et"
   }
  }
  AFM_DiDVehicleEntry "{0CFCD7E187F0242F}" {
   m_sVehiclePrefab "{0FBF8F010F81A4E5}Prefabs/Vehicles/Wheeled/LAV25/LAV25.et"
   m_CrewConfig AFM_CrewConfig "{BC898B4E750F6583}" {
    m_sDriverPrefab "{E1CB513B8B9B08F4}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Crew.et"
    m_sGunnerPrefab "{E1CB513B8B9B08F4}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Crew.et"
   }
  }
 }
 m_sMortarComposition "{02CEBD7F3DA12C05}Prefabs/Compositions/DiD_MortarComposition_US.et"
 m_MortarCrew AFM_CrewConfig "{46397B47B80372B0}" {
  m_sDriverPrefab ""
  m_sGunnerPrefab "{26A9756790131354}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Rifleman.et"
  m_bSpawnDriver 0
  m_bNoTurretDismount 0
 }
 m_aHelicopters {
  "{CB4D4CF7E887B2D0}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HEDP.et"
 }
 m_sHelicopterCrewGroup "{BF78D4AAF08466CD}Prefabs/Groups/BLUFOR/REAPER_US_HelicopterCrew.et"
 m_sCowabungaGroup "{EACD97CF4A702FAE}Prefabs/Groups/BLUFOR/Group_US_Base.et"
 m_aCowabungaCharacters {
  "{2F912ED6E399FF47}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Unarmed.et"
 }
 m_aPlayerCharacters {
  "{0B3167BB0FB68110}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_PL.et"
  "{4FBA24F7BB43E17D}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Sergeant.et"
  "{C9E4FEAF5AAC8D8C}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Medic.et"
  "{E398E44759DA1A43}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_TL.et"
  "{5B1996C05B1E51A4}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_AR.et"
  "{84029128FA6F6BB9}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_GL.et"
  "{27BF1FF235DD6036}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_LAT.et"
  "{26A9756790131354}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_Rifleman.et"
 }
 m_sExtractionHelicopter "{BDE43262FC05B4D7}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_empty_sharkNose.et"
 m_sExtractionCrewGroup "{BF78D4AAF08466CD}Prefabs/Groups/BLUFOR/REAPER_US_HelicopterCrew.et"
}