AFM_DiDSupplyConfig {
 m_iDefaultStartingSupplies 1050
 m_aStartingSuppliesPerZone {
  2400
  1500
  1050
 }
 m_iCacheMaximum 4500
 m_fCarryOverFraction 0.5
 m_iCompositionRefundPercentage 50
 m_iRewardPerInfantryKill 3
 m_iRewardPerVehicleKill 75
 m_iRewardPerMinuteHeld 38
 m_iRewardPerHelicopterKill 375
 m_iRewardPerMortarKill 225
 m_iRewardPerWaveCleared 225
 m_iKillIncomeCapPerZone 900
}
