AFM_DiDSupplyConfig {
 m_iDefaultStartingSupplies 700
 m_aStartingSuppliesPerZone {
  1600
  1000
  700
 }
 m_iCacheMaximum 3000
 m_fCarryOverFraction 0.5
 m_iCompositionRefundPercentage 25
 m_iRewardPerInfantryKill 2
 m_iRewardPerVehicleKill 50
 m_iRewardPerMinuteHeld 25
 m_iRewardPerHelicopterKill 250
 m_iRewardPerMortarKill 150
 m_iRewardPerWaveCleared 150
 m_iKillIncomeCapPerZone 600
}
