AFM_DiDSupplyConfig {
 m_iDefaultStartingSupplies 1400
 m_aStartingSuppliesPerZone {
  3200
  2000
  1400
 }
 m_iCacheMaximum 6000
 m_fCarryOverFraction 1.0
 m_iCompositionRefundPercentage 100
 m_iRewardPerInfantryKill 4
 m_iRewardPerVehicleKill 100
 m_iRewardPerMinuteHeld 50
 m_iRewardPerHelicopterKill 500
 m_iRewardPerMortarKill 300
 m_iRewardPerWaveCleared 300
 m_iKillIncomeCapPerZone 1200
}
