SCR_MissionHeader {
 World "{2C3779FE42566F58}Worlds/DiD_BelleauWoods.ent"
 m_sName "Defense In Depth - Balleau Woods"
 m_sAuthor "nielu"
 m_sDescription "Get trenched."
 m_sGameMode "DiD"
 m_iPlayerCount 32
 m_AFM_DiDDefaultPhase AFM_DiDPhaseSettings "{6A870B2F22264A87}" {
  m_iPrepareTimeSeconds 300
  m_iDefenseTimeSeconds 600
  m_iFailureTimeSeconds 300
  m_iTicketsPerPlayer 15
  m_fTicketMultiplier 1
  m_iMinTickets 60
  m_iMaxTickets 240
  m_iMaxAICount 0
 }
}