MenuManager {
 MenuPresets {
  MenuPreset AFM_DiDSetupMenu {
   Layout "{7A543F744922218A}UI/layouts/Setup/DiD_SetupMenu.layout"
   ActionContext "MenuWithEditorContext"
   Class "AFM_DiDSetupMenu"
  }
 }
}