ActionManager {
 Contexts {
  ActionContext AFM_SpectatorContext {
   Priority 61
   Flags 0x2 0
   Actions {
    Action AFM_SpectatorNext {
     InputSource InputSourceSum "{1A4725333E70D38D}" {
      Sources {
       InputSourceValue "{9463D383D723F8FC}" {
        FilterPreset "click"
        Input "keyboard:KC_R"
        Filter InputFilterClick "{36941315EF0BCBDE}" {
        }
       }
      }
     }
    }
    Action AFM_SpectatorPrevious {
     InputSource InputSourceSum "{6AEAFF4DF201686C}" {
      Sources {
       InputSourceValue "{EDBFB9D9C101F332}" {
        FilterPreset "click"
        Input "keyboard:KC_E"
        Filter InputFilterClick "{8B6CC7942414A26E}" {
        }
       }
      }
     }
    }
    Action AFM_SpectatorFree {
     InputSource InputSourceSum "{740C5554EF7C68D3}" {
      Sources {
       InputSourceValue "{391572D0AE1DE5A3}" {
        FilterPreset "click"
        Input "keyboard:KC_F"
        Filter InputFilterClick "{E05587AB02B2FFA6}" {
        }
       }
      }
     }
    }
   }
  }
  ActionContext AFM_VoiceContext {
   Priority 110
   Flags 0x2 0
   Actions {
    Action AFM_VoiceTalk {
     InputSource InputSourceSum "{749865E8F27F8DE2}" {
      Sources {
       InputSourceValue "{A17028F965B01340}" {
        FilterPreset "hold"
        Input "keyboard:KC_T"
       }
      }
     }
    }
   }
  }
 }
}