SCR_RankContainer {
 m_aRanks {
  SCR_RankInfoCampaign "{6A7CC57DCC95F835}" {
   m_iRequiredXP -50
   m_sRankName "#AR-Rank_WestPrivate"
   m_sRankNameUpper "#AR-Rank_WestPrivate-UC"
   m_sRankNameShort "#AR-Rank_WestPrivateShort"
   m_sInsignia "AR_Rank_OR-2"
   m_iRequestCD 600
   m_iRadioRespawnCooldown 45
   m_iFastTravelCooldown 600
   m_eRadioMsg PROMOTION_PRIVATE
  }
  SCR_RankInfoCampaign "{6A7CC57DCC95F833}" {
   m_iRank CORPORAL
   m_iRequiredXP 150
   m_sRankName "#AR-Rank_WestCorporal"
   m_sRankNameUpper "#AR-Rank_WestCorporal-UC"
   m_sRankNameShort "#AR-Rank_WestCorporalShort"
   m_sInsignia "AR_Rank_OR-4_C"
   m_iRequestCD 600
   m_iRadioRespawnCooldown 42
   m_iFastTravelCooldown 540
   m_eRadioMsg PROMOTION_CORPORAL
  }
  SCR_RankInfoCampaign "{6A7CC57DCC95F832}" {
   m_iRank SERGEANT
   m_iRequiredXP 600
   m_sRankName "#AR-Rank_WestSergeant"
   m_sRankNameUpper "#AR-Rank_WestSergeant-UC"
   m_sRankNameShort "#AR-Rank_WestSergeantShort"
   m_sInsignia "AR_Rank_OR-5"
   m_iRequestCD 450
   m_iRadioRespawnCooldown 39
   m_iFastTravelCooldown 480
   m_eRadioMsg PROMOTION_SERGEANT
  }
  SCR_RankInfoCampaign "{6A7CC57DCC95F831}" {
   m_iRank LIEUTENANT
   m_iRequiredXP 1200
   m_sRankName "#AR-Rank_WestLieutenant"
   m_sRankNameUpper "#AR-Rank_WestLieutenant-UC"
   m_sRankNameShort "#AR-Rank_WestLieutenantShort"
   m_sInsignia "AR_Rank_OF-1_1st"
   m_iRequestCD 300
   m_iRadioRespawnCooldown 36
   m_iFastTravelCooldown 480
   m_eRadioMsg PROMOTION_LIEUTENANT
  }
  SCR_RankInfoCampaign "{6A7CC57DCC95F830}" {
   m_iRank CAPTAIN
   m_iRequiredXP 2100
   m_sRankName "#AR-Rank_WestCaptain"
   m_sRankNameUpper "#AR-Rank_WestCaptain-UC"
   m_sRankNameShort "#AR-Rank_WestCaptainShort"
   m_sInsignia "AR_Rank_OF-2"
   m_iRequestCD 150
   m_iRadioRespawnCooldown 33
   m_iFastTravelCooldown 360
   m_eRadioMsg PROMOTION_CAPTAIN
  }
  SCR_RankInfoCampaign "{6A7CC57DCC95F84F}" {
   m_iRank MAJOR
   m_iRequiredXP 3300
   m_sRankName "#AR-Rank_WestMajor"
   m_sRankNameUpper "#AR-Rank_WestMajor-UC"
   m_sRankNameShort "#AR-Rank_WestMajorShort"
   m_sInsignia "AR_Rank_OF-3"
   m_iRequestCD 5
   m_eRadioMsg PROMOTION_MAJOR
  }
 }
}