SCR_GameOverScreenConfig {
 m_aGameOverScreens {
  SCR_BaseGameOverScreenInfo "{CBED39FB50ADC5E8}" {
   m_GameOverScreenId AFM_DID_DEFENDERS_WIN
   m_GameOverContentLayout "{1BF526A0C79AB999}UI/layouts/Debriefing/DiD_GameOverContent.layout"
   m_OptionalParams SCR_BaseGameOverScreenInfoOptional "{8A5C6F83D4901AF3}" {
    m_sTitle "#AR-MatchResult_Victory-UC"
    m_sSubtitle "Defenders win"
    m_sAudioOneShot "SOUND_ONVICTORY"
   }
  }
  SCR_BaseGameOverScreenInfo "{9FBB21EC048F2009}" {
   m_GameOverScreenId AFM_DID_ATTACKERS_WIN
   m_GameOverContentLayout "{1BF526A0C79AB999}UI/layouts/Debriefing/DiD_GameOverContent.layout"
   m_OptionalParams SCR_BaseGameOverScreenInfoOptional "{CAEB2512D82CEC76}" {
    m_sTitle "#AR-MatchResult_Defeat-UC"
    m_sSubtitle "Attackers win"
    m_sAudioOneShot "SOUND_ONDEFEAT"
   }
  }
 }
}